### ISSUE TITLE
Django-redis > 4.4.4

### ISSUE THREAD

**Issue by tarsil** [SpatialBuzz/django-redis-sentinel#6]
Hi,

I've tried to run with django-redis 4.9+ and it fails the `get_client` and the reason for that is because now `django-redis` is using 2 more parameters.

Is there any plan to upgrade the current sentinel?

Thanks,
Tiago

**Comment by ryan-shaw** [comment]
Hi, 

There is no plan to upgrade this module at the moment, the setup.py specifies the `django-redis` versions that are supported: `django-redis>=3.8.0,<=4.4.4`

**Comment by dpaluch-rp** [comment]
Hi @ryan-shaw, 

What was the purpose to stick with <=4.4.4 instead of 4.5 ?
Python 2 support?
